# Generated by Django 5.0 on 2023-12-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='analistas',
            new_name='analista',
        ),
    ]
