# Generated by Django 5.0 on 2024-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0005_alter_analista_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='cargo',
            field=models.TextField(max_length=255),
        ),
    ]
