# Generated by Django 5.0 on 2024-01-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0006_alter_analista_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analista',
        ),
    ]
