# Generated by Django 5.0 on 2024-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_projeto', '0007_delete_analista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id_analista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('celular', models.TextField(max_length=255)),
                ('canal', models.TextField(max_length=255)),
                ('cargo', models.TextField(max_length=255)),
                ('oferta', models.TextField(choices=[('RM', 'RM'), ('TOTVS MODA', 'TOTVS MODA'), ('WINTHOR', 'WINTHOR'), ('JURÍDICO', 'JURÍDICO'), ('PROTHEUS', 'PROTHEUS'), ('DATASUL', 'DATASUL'), ('TOTVS AGRO', 'TOTVS AGRO'), ('FLUIG', 'FLUIG'), ('GOOD DATA', 'GOOD DATA'), ('COMERCIAL', 'COMERCIAL'), ('LOGIX', 'LOGIX'), ('E-COMMERCE', 'E-COMMERCE'), ('COMEX', 'COMEX'), ('SAÚDE', 'SAÚDE'), ('CONSINCO', 'CONSINCO'), ('CMNET', 'CMNET'), ('DBA', 'DBA'), ('HOSPITALITY', 'HOSPITALITY')])),
                ('modulo', models.TextField(max_length=255)),
                ('submodulo', models.TextField(max_length=255)),
            ],
        ),
    ]
