# Generated by Django 5.0 on 2024-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='oferta',
            field=models.CharField(choices=[('RM', 'RM'), ('TOTVS MODA', 'TOTVS MODA'), ('WINTHOR', 'WINTHOR'), ('JURÍDICO', 'JURÍDICO'), ('PROTHEUS', 'PROTHEUS'), ('DATASUL', 'DATASUL'), ('TOTVS AGRO', 'TOTVS AGRO'), ('FLUIG', 'FLUIG'), ('GOOD DATA', 'GOOD DATA'), ('COMERCIAL', 'COMERCIAL'), ('LOGIX', 'LOGIX'), ('E-COMMERCE', 'E-COMMERCE'), ('COMEX', 'COMEX'), ('SAÚDE', 'SAÚDE'), ('CONSINCO', 'CONSINCO'), ('CMNET', 'CMNET'), ('DBA', 'DBA'), ('HOSPITALITY', 'HOSPITALITY')], max_length=255),
        ),
    ]
