# Generated by Django 5.0 on 2024-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0010_oferta_unidade_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='canal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analista',
            name='cargo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analista',
            name='celular',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analista',
            name='modulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analista',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analista',
            name='submodulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='canal',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
