# Generated by Django 5.0 on 2024-01-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0011_alter_analista_canal_alter_analista_cargo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analista',
        ),
        migrations.RemoveField(
            model_name='canal',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
