OFERTA_CHOICES = [
    ("RM", "RM"),
    ("TOTVS MODA", "TOTVS MODA"),
    ("WINTHOR", "WINTHOR"),
    ("JURÍDICO", "JURÍDICO"),
    ("PROTHEUS", "PROTHEUS"),
    ("DATASUL", "DATASUL"),
    ("TOTVS AGRO", "TOTVS AGRO"),
    ("FLUIG", "FLUIG"),
    ("GOOD DATA", "GOOD DATA"),
    ("COMERCIAL", "COMERCIAL"),
    ("LOGIX", "LOGIX"),
    ("E-COMMERCE", "E-COMMERCE"),
    ("COMEX", "COMEX"),
    ("SAÚDE", "SAÚDE"),
    ("CONSINCO", "CONSINCO"),
    ("CMNET", "CMNET"),
    ("DBA", "DBA"),
    ("HOSPITALITY", "HOSPITALITY")
]